import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css';


// Components
import { Box, Text } from "@chakra-ui/react";
import Nav from '../Components/Nav/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>Xerucide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Share+Tech&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header className="load-in">
        <Box className="noise"> </Box>
        <Box sx={styles.container}>
        <Nav/>
          <Box
            sx={styles.headerContainer}
            style={{ transform: "translate (-50%, calc(-50%))" }}
          >
             
            <div className="title before-load">
              <Text className="glitch" as="h1" color="#ffff" sx={styles.headerText}>
                <span aira-hidden="true">Xerucide</span>
                Xerucide
                <span aira-hidden="true">Xerucide</span>
              </Text>
            </div>
            <Text as="h2">Coming Soon</Text>
          </Box>
        </Box>
      </header>
  
    </>
  );
}


const styles = {
  container: {
    backgroundImage: "url('/bg.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100vh",
    zIndex: "10",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },

  headerContainer: {
    textAlign: "center",
  },

  noiseLayer: {
    zIndex: "900000",
    backgroundImage: 'url("/noise")',
    backgroundSize: "cover",
  },
  headerText: {
   
  }

};
