import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css';


// Components
import { Box, Text, Button } from "@chakra-ui/react";
import Nav from '../Components/Nav/index';
import Homepage from '../Components/Homepage/Homepage';
import UnderConstruction from "../Components/UnderConstruction";

export default function Home() {
  return (
    <>
      <Head>
        <title>Batchforum</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&family=Russo+One&display=swap" rel="stylesheet"/>
        <link
          href="https://fonts.googleapis.com/css2?family=Share+Tech&display=swap"
          rel="stylesheet"
        />
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&display=swap" rel="stylesheet"/>
      </Head>
   <div>
     <UnderConstruction/>
   </div>

 


  
    </>
  );
}


const styles = {
  container: {
    backgroundImage: "url('/RealBg.webp')",
    backgroundSize: "cover",
    backgroundPosition: "right",
    height: "100vh",
    zIndex: "10",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: 'fixed'
  },

  headerContainer: {
    textAlign: "center",
  },

  noiseLayer: {
    zIndex: "900000",
    backgroundImage: 'url("/noise")',
    backgroundSize: "cover",
  },

  headerText: {
   
  }

};
